---
# Source: paths-example/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nginx
  selector:
    app: test
